import { restaurant1Img, restaurant2Img, restaurant3Img, restaurant4Img, restaurant5Img, restaurant6Img, restaurant7Img, restaurant8Img } from "../assets/images/images";

export const restaurantsData = [
    {
      id: 901,
      seller_id: 701,
      name: "Healthy Feast Corner",
      total_dishes: 34,
      total_sales: 425,
      address:
        "2123 Osprey the Blue Mountains, Townline, Feversham, ON NOC 1CO, Canada",
      categories: [1, 2],
      logo: restaurant1Img,
      contact_no: 1078832848,
      email: "hbruggen0@narod.ru",
    },
    {
      id: 902,
      seller_id: 702,
      name: "Farmhouse Dish Heaven",
      total_dishes: 12,
      total_sales: 1234,
      address: "2045 Scotch Line, Essa, Ontario, L9R 1V2, Alliston, CA",
      categories: [2, 3],
      logo: restaurant2Img,
      contact_no: 2847899814,
      email: "dsoden1@fda.gov",
    },
    {
      id: 903,
      seller_id: 703,
      name: "Kitchen Creation",
      total_dishes: 14,
      total_sales: 42,
      address: "6058 Townhigh Mountains, Sideroad, Clarksburg, ON.",
      categories: [4, 5],
      logo: restaurant3Img,
      contact_no: 2816686226,
      email: "lhillen2@dyndns.org",
    },
    {
      id: 904,
      seller_id: 704,
      name: "Country Cooking Cove",
      total_dishes: 53,
      total_sales: 2452,
      address: "A-67 Concession 8, Nottawasaga RD, Glen Huron, Poland",
      categories: [5, 6],
      logo: restaurant4Img,
      contact_no: 1102607941,
      email: "knewsome3@alexa.com",
    },
    {
      id: 905,
      seller_id: 705,
      name: "Gourmet Flavor nook",
      total_dishes: 50,
      total_sales: 1506,
      address:
        "2123 Osprey the Blue Mountains, Townline, Feversham, ON NOC 1CO, Canada",
      categories: [6, 7],
      logo: restaurant5Img,
      contact_no: 9422719236,
      email: "rsclater4@nydailynews.com",
    },
    {
      id: 906,
      seller_id: 706,
      name: "Culinary Craft Cabin",
      total_dishes: 10,
      total_sales: 1052,
      address: "3,4 - Twilight Bungalows, Sideroad, Clarksburg, Russia",
      categories: [7, 1],
      logo: restaurant6Img,
      contact_no: 6692668539,
      email: "apluthero5@tuttocitta.it",
    },
    {
      id: 907,
      seller_id: 707,
      name: "Rustic Spice Shack",
      total_dishes: 15,
      total_sales: 257,
      address: "1003 Nusha Apartment, Townline st., Helsinki, NGC Road , Finland",
      categories: [6, 2],
      logo: restaurant7Img,
      contact_no: 4667129090,
      email: "wconew6@qq.com",
    },
    {
      id: 908,
      seller_id: 708,
      name: "Savory Bites Cafe",
      total_dishes: 28,
      total_sales: 357,
      address: "784 Flowsome Avenue st., Shine Road, Sa Francisco , USA 547215",
      categories: [5, 3],
      logo: restaurant8Img,
      contact_no: 4102508252,
      email: "cbogies7@disqus.com",
    },
  ];
  